### PR TITLE
Small blog post tweaks

### PR DESCRIPTION
**Pull request by crcastle**
Each commit should be self-explanatory.  Hit me up if they aren't clear!

### CODE REVIEW

**Comment by andkon** [comment]
@SophieDeBenedetto just some context - I had Chris try to deploy the app. Looks like a few things were hardcoded that made it so if you hit the 'deploy to heroku' button then it wouldn't work as advertised. This should fix those button deploys.

**Comment by crcastle** [comment]
Just saw this sorry for delay. My pull request just fixes a few blog text
issues. Not the deploy issue. Great tutorial Sophie!

**Comment by SophieDeBenedetto** [comment]
thanks for your feedback @crcastle! The deploy issue _should_ be all fixed now.

**Comment by crcastle** [comment]
Hey @SophieDeBenedetto, just did a deploy and everything looks to be working as expected!  Thanks.

**Pull request merged**
